name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        required: false

jobs:
  job1:
    uses: ./.github/workflows/build.yml

  job2:
    runs-on: ubuntu-latest
    needs: job1
    
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}
  job3:
    uses: ./.github/workflows/import.yml
  job4:
    runs-on: ubuntu-latest
    needs: job3
    
    steps:
      - run: echo ${{ needs.job3.outputs.firstword }} ${{ needs.job3.outputs.secondword }}
