name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4

        - uses: .github/actions/build-action

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}
  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
        - uses: actions/checkout@v4

        - uses: .github/actions/import-action

  job4:
    runs-on: ubuntu-latest
    needs: job3
    steps:
      - run: echo ${{ needs.job3.outputs.firstword }} ${{ needs.job3.outputs.secondword }}
