name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        required: false

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: call build action
          uses: ./.github/actions/build-action

  job2:
    runs-on: ubuntu-latest
    needs: job1
    
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}
